--Social@Panther
--Terence Sperringer (tps23)
--Sizhe Sun (sis61)

--Generated Data for Social@Panther

--THIS CLEARS ALL PROFILES!!!
DELETE FROM PROFILE;

--INSERT USERS:
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (1, 'leon rivera', 'leon.rivera@example.com','tinkerbe', TO_DATE('1994-11-27 13:20:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (2, 'ricky rose', 'ricky.rose@example.com','lander', TO_DATE('1980-04-08 04:46:11', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (3, 'karen terry', 'karen.terry@example.com','deadman', TO_DATE('1955-04-26 06:21:51', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (4, 'sean lowe', 'sean.lowe@example.com','phillip', TO_DATE('1969-07-24 02:15:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (5, 'ethan brar', 'ethan.brar@example.com','hewlett', TO_DATE('1974-05-05 19:58:02', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (6, 'sergio montero', 'sergio.montero@example.com','tian', TO_DATE('1981-11-13 21:49:40', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (7, 'sina da rosa', 'sina.darosa@example.com','bobafett', TO_DATE('1961-06-05 06:08:54', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (8, 'phoebe barnes', 'phoebe.barnes@example.com','chan', TO_DATE('1961-12-08 12:13:07', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (9, 'ella griffin', 'ella.griffin@example.com','fishbone', TO_DATE('1955-05-31 09:00:57', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (10, 'lauren garza', 'lauren.garza@example.com','bobcat', TO_DATE('1946-04-19 18:19:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (11, 'clara gagnon', 'clara.gagnon@example.com','access', TO_DATE('1950-09-09 19:59:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (12, 'addison novak', 'addison.novak@example.com','hitman', TO_DATE('1966-08-28 11:37:01', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (13, 'tina moser', 'tina.moser@example.com','1962', TO_DATE('1974-01-26 04:38:26', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (14, 'amy nichols', 'amy.nichols@example.com','kathy', TO_DATE('1963-10-17 15:08:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (15, 'deniz saygıner', 'deniz.saygıner@example.com','american', TO_DATE('1989-09-10 19:30:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (16, 'elizabeth margaret', 'elizabeth.margaret@example.com','istheman', TO_DATE('1953-01-09 17:45:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (17, 'frank anderson', 'frank.anderson@example.com','native', TO_DATE('1982-06-30 04:09:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (18, 'auguste vincent', 'auguste.vincent@example.com','bowwow', TO_DATE('1963-02-13 08:10:54', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (19, 'melinda lee', 'melinda.lee@example.com','snapon', TO_DATE('1951-07-27 11:47:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (20, 'randy perry', 'randy.perry@example.com','static', TO_DATE('1984-04-19 09:53:05', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (21, 'gordon kuhn', 'gordon.kuhn@example.com','starwars', TO_DATE('1946-08-22 11:02:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (22, 'albert blanco', 'albert.blanco@example.com','mental', TO_DATE('1985-05-04 04:29:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (23, 'juliette olivier', 'juliette.olivier@example.com','magician', TO_DATE('1963-04-01 09:14:11', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (24, 'dennis witt', 'dennis.witt@example.com','cartman', TO_DATE('1984-09-25 19:57:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (25, 'tilde rasmussen', 'tilde.rasmussen@example.com','john316', TO_DATE('1974-02-26 06:52:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (26, 'silje kristensen', 'silje.kristensen@example.com','esther', TO_DATE('1973-07-31 06:24:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (27, 'quinn morris', 'quinn.morris@example.com','mattie', TO_DATE('1989-11-07 07:46:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (28, 'armano nelemans', 'armano.nelemans@example.com','fruity', TO_DATE('1972-01-06 17:53:28', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (29, 'susie harris', 'susie.harris@example.com','vampire', TO_DATE('1953-03-18 00:54:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (30, 'amália da conceição', 'amália.daconceição@example.com','blues1', TO_DATE('1956-01-16 23:34:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (31, 'izolina ribeiro', 'izolina.ribeiro@example.com','chicks', TO_DATE('1965-06-24 08:23:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (32, 'emeline guillaume', 'emeline.guillaume@example.com','clinton', TO_DATE('1968-07-26 20:39:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (33, 'inès gerard', 'inès.gerard@example.com','lian', TO_DATE('1968-07-02 10:38:26', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (34, 'marceau clement', 'marceau.clement@example.com','jumper', TO_DATE('1971-07-25 04:58:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (35, 'leslie morrison', 'leslie.morrison@example.com','saigon', TO_DATE('1984-02-14 18:04:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (36, 'viljami joki', 'viljami.joki@example.com','hohoho', TO_DATE('1979-02-12 00:43:57', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (37, 'alexia masson', 'alexia.masson@example.com','pacific', TO_DATE('1980-04-12 23:18:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (38, 'rosário peixoto', 'rosário.peixoto@example.com','marine', TO_DATE('1987-10-04 15:18:08', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (39, 'elena sturm', 'elena.sturm@example.com','deborah', TO_DATE('1970-10-11 22:19:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (40, 'luan penninga', 'luan.penninga@example.com','nicolas', TO_DATE('1952-02-23 10:17:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (41, 'eléonore roussel', 'eléonore.roussel@example.com','babies', TO_DATE('1962-12-08 05:36:02', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (42, 'annika busch', 'annika.busch@example.com','bizkit', TO_DATE('1986-08-31 23:57:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (43, 'niilo paavola', 'niilo.paavola@example.com','steeler', TO_DATE('1965-01-22 20:54:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (44, 'melissa john', 'melissa.john@example.com','cookies', TO_DATE('1959-10-22 03:35:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (45, 'sylvan reedijk', 'sylvan.reedijk@example.com','thx1138', TO_DATE('1973-06-23 14:11:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (46, 'thiago girard', 'thiago.girard@example.com','1007', TO_DATE('1982-06-27 09:51:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (47, 'elóides teixeira', 'elóides.teixeira@example.com','atlanta', TO_DATE('1979-02-24 12:50:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (48, 'micheal long', 'micheal.long@example.com','taxman', TO_DATE('1982-08-16 13:51:51', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (49, 'timmothy pearson', 'timmothy.pearson@example.com','louise', TO_DATE('1971-09-09 03:12:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (50, 'natalie wright', 'natalie.wright@example.com','britney', TO_DATE('1995-06-03 05:01:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (51, 'heather baker', 'heather.baker@example.com','models', TO_DATE('1969-05-26 11:20:05', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (52, 'ferdinand scholz', 'ferdinand.scholz@example.com','typhoon', TO_DATE('1954-10-24 21:31:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (53, 'macit oraloğlu', 'macit.oraloğlu@example.com','islander', TO_DATE('1951-07-31 02:04:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (54, 'brett davis', 'brett.davis@example.com','blue99', TO_DATE('1964-06-02 19:13:42', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (55, 'felix willis', 'felix.willis@example.com','goat', TO_DATE('1962-12-06 19:06:40', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (56, 'davine reimert', 'davine.reimert@example.com','student', TO_DATE('1987-08-06 08:26:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (57, 'fatma taşlı', 'fatma.taşlı@example.com','gateway1', TO_DATE('1975-08-05 03:06:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (58, 'harper tremblay', 'harper.tremblay@example.com','191919', TO_DATE('1986-06-28 00:50:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (59, 'fabian renner', 'fabian.renner@example.com','olympia', TO_DATE('1991-11-09 19:18:29', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (60, 'begüm çapanoğlu', 'begüm.çapanoğlu@example.com','passport', TO_DATE('1984-10-28 19:43:08', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (61, 'joaquin pascual', 'joaquin.pascual@example.com','gooner', TO_DATE('1947-04-05 00:39:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (62, 'brittany soto', 'brittany.soto@example.com','hooter', TO_DATE('1970-04-30 09:04:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (63, 'hudson moore', 'hudson.moore@example.com','xxxxxx1', TO_DATE('1985-08-27 14:45:48', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (64, 'peter lynch', 'peter.lynch@example.com','ping', TO_DATE('1993-03-29 21:27:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (65, 'arttu aro', 'arttu.aro@example.com','alissa', TO_DATE('1946-10-25 20:37:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (66, 'eetu wuollet', 'eetu.wuollet@example.com','samuel1', TO_DATE('1964-02-20 11:31:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (67, 'shannon washington', 'shannon.washington@example.com','yousuck', TO_DATE('1976-04-24 07:56:26', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (68, 'felix brückner', 'felix.brückner@example.com','cunts', TO_DATE('1994-05-07 15:58:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (69, 'barbara carlson', 'barbara.carlson@example.com','pool6123', TO_DATE('1980-12-31 04:46:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (70, 'ivanice cardoso', 'ivanice.cardoso@example.com','cannon', TO_DATE('1964-10-12 11:59:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (71, 'kerim yazıcı', 'kerim.yazıcı@example.com','patch', TO_DATE('1960-05-07 09:00:37', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (72, 'mathilde jørgensen', 'mathilde.jørgensen@example.com','hong', TO_DATE('1993-02-20 15:02:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (73, 'elisa giraud', 'elisa.giraud@example.com','doodle', TO_DATE('1947-02-20 13:51:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (74, 'mila chevalier', 'mila.chevalier@example.com','1029', TO_DATE('1988-08-01 10:31:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (75, 'laura jensen', 'laura.jensen@example.com','silly', TO_DATE('1950-04-15 11:55:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (76, 'adam fabre', 'adam.fabre@example.com','pool6123', TO_DATE('1965-04-06 06:45:47', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (77, 'ronnie newman', 'ronnie.newman@example.com','holein1', TO_DATE('1992-03-06 01:43:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (78, 'judith heller', 'judith.heller@example.com','bone', TO_DATE('1954-05-18 20:58:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (79, 'jesus oliver', 'jesus.oliver@example.com','505050', TO_DATE('1958-08-17 19:10:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (80, 'hannah wilson', 'hannah.wilson@example.com','wg8e3wjf', TO_DATE('1947-11-08 09:55:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (81, 'luca rodrigues', 'luca.rodrigues@example.com','lighter', TO_DATE('1980-11-22 11:06:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (82, 'necati özgörkey', 'necati.özgörkey@example.com','miami', TO_DATE('1994-08-13 05:20:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (83, 'hélio caldeira', 'hélio.caldeira@example.com','meatball', TO_DATE('1981-08-07 12:04:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (84, 'mélissa blanchard', 'mélissa.blanchard@example.com','onion', TO_DATE('1945-01-03 03:32:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (85, 'gül gönültaş', 'gül.gönültaş@example.com','gmoney', TO_DATE('1967-05-20 17:31:49', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (86, 'alicia baker', 'alicia.baker@example.com','lexingky', TO_DATE('1951-05-07 19:39:49', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (87, 'eric cole', 'eric.cole@example.com','wilbur', TO_DATE('1946-10-12 04:50:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (88, 'ramon black', 'ramon.black@example.com','vaughn', TO_DATE('1971-04-03 09:07:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (89, 'vedat balcı', 'vedat.balcı@example.com','beatles1', TO_DATE('1945-09-21 23:44:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (90, 'eli harris', 'eli.harris@example.com','total', TO_DATE('1992-08-25 04:08:57', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (91, 'lily herrera', 'lily.herrera@example.com','research', TO_DATE('1958-04-14 02:20:08', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (92, 'zachary li', 'zachary.li@example.com','daisy1', TO_DATE('1962-09-23 14:20:07', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (93, 'amy garcia', 'amy.garcia@example.com','linda1', TO_DATE('1979-01-20 10:01:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (94, 'aubrey cunningham', 'aubrey.cunningham@example.com','pppppp', TO_DATE('1990-04-13 14:31:32', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (95, 'jon mcdonalid', 'jon.mcdonalid@example.com','jsbach', TO_DATE('1961-12-23 05:00:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (96, 'jade tremblay', 'jade.tremblay@example.com','fishy', TO_DATE('1965-12-15 11:09:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (97, 'mestan erbay', 'mestan.erbay@example.com','8j4ye3uz', TO_DATE('1994-08-26 13:52:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (98, 'julie lacroix', 'julie.lacroix@example.com','destroy', TO_DATE('1959-08-30 00:49:11', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (99, 'crystal beck', 'crystal.beck@example.com','castor', TO_DATE('1976-06-29 12:30:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROFILE (userID, name, email, password, date_of_birth) VALUES (100, 'timo toering', 'timo.toering@example.com','felix1', TO_DATE('1987-11-13 10:23:57', 'YYYY-MM-DD HH24:MI:SS'));
